feat: Финальный проект 7 спринта
EvgeniyaaaD/java-kanban pull request #3
Opened 2024-04-01 00:56 UTC by EvgeniyaaaD

2024-04-01 16:39 UTC, Yang-Pi requested changes
Общий комментарий: Добавь пакеты lib и out в .gitognore

2024-04-01 16:39 UTC, Yang-Pi commented on lib/apiguardian-api-1.1.2.jar
Добавь пакеты lib и out в .gitignore

2024-04-01 16:39 UTC, Yang-Pi commented on src/service/Managers.java
> +        return new InMemoryTaskManager();
Было верно) теперь проблема с внедрением зависимостей

"При такой реализации менджер истории в оперативной памяти жестко зашивается в менеджер задач. А если понадобится сохранять историю в отдельный файл или базу данных. Стоит использовать подход к инициализации поля класса через аргумент конструктора, это называется "внедрением зависимости" (dependency injection)."

2024-04-01 16:39 UTC, Yang-Pi commented on src/service/FileBackedTaskManager.java
> +    public void createTaskFromFile(Task task) {
Слишком широкий модификатор доступ у метода

2024-04-01 16:39 UTC, Yang-Pi commented on src/service/FileBackedTaskManager.java
> +        save();
Этот метод вызывается при считывании информации из файла, те файл перезаписывается в момент считывания (да, формально все уже считалось и хранится в мапе, но сохранение все равно излишне и занимает память и время программы)

2024-04-01 16:39 UTC, Yang-Pi commented on src/service/FileBackedTaskManager.java
> +        Task task = super.findTaskById(id);
В качестве улучшения можно добавить проверку, что если метод super вернул null, то только тогда имеет смысл вызывать сохранение, потому что иначе никаких изменений не было сделано

2024-04-01 16:39 UTC, Yang-Pi commented on src/service/FileBackedTaskManager.java
> +        return fileBackedTasksManager;
Важный момент - для задач был задан id, но затем при создании новых будет id cнова генерироваться, но при текущей реализации эта генерация будет с нуля, что приведет к дублированию.

2024-04-01 20:10 UTC, EvgeniyaaaD commented on src/service/Managers.java
> +        return new InMemoryTaskManager();
Вернула к верной версии (предыдущей)

2024-04-02 14:40 UTC, Yang-Pi requested changes

2024-04-02 14:40 UTC, Yang-Pi commented on src/service/FileBackedTaskManager.java
> +    public static void loadFromFile(File file, FileBackedTaskManager fileBackedTaskManager) {
У этого метода неверный список параметров - это фабричный метод фактически, те он создает менеджер задач, поэтому не должен никак принимать в качестве параметров уже созданный менеджер

2024-04-02 14:40 UTC, Yang-Pi commented on src/service/FileBackedTaskManager.java
> +        fileBackedTaskManager.createFromFile(allTasksFromFile);
Проблема id все еще актуальна
"Важный момент - для задач был задан id, но затем при создании новых будет id cнова генерироваться, но при текущей реализации эта генерация будет с нуля, что приведет к дублированию."

2024-04-02 19:16 UTC, Yang-Pi approved these changes

2024-04-02 21:56 UTC, merged